// Code generated by MockGen. DO NOT EDIT.
// Source: ./service.go
//
// Generated by this command:
//
//	mockgen -source=./service.go -destination=./service_mock.go -package=service
//

// Package service is a generated GoMock package.
package service

import (
	reflect "reflect"

	types "github.com/nutanalabs/eta-service/internal/types"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// FetchEta mocks base method.
func (m *MockService) FetchEta(request *types.FetchEtaRequest) ([]types.FetchEtaResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchEta", request)
	ret0, _ := ret[0].([]types.FetchEtaResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchEta indicates an expected call of FetchEta.
func (mr *MockServiceMockRecorder) FetchEta(request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchEta", reflect.TypeOf((*MockService)(nil).FetchEta), request)
}

// InsertRestaurantComponents mocks base method.
func (m *MockService) InsertRestaurantComponents(request *types.InsertRestaurantComponentsRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertRestaurantComponents", request)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertRestaurantComponents indicates an expected call of InsertRestaurantComponents.
func (mr *MockServiceMockRecorder) InsertRestaurantComponents(request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertRestaurantComponents", reflect.TypeOf((*MockService)(nil).InsertRestaurantComponents), request)
}

// InsertSublocalityComponents mocks base method.
func (m *MockService) InsertSublocalityComponents(request *types.InsertSublocalityComponentsRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertSublocalityComponents", request)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertSublocalityComponents indicates an expected call of InsertSublocalityComponents.
func (mr *MockServiceMockRecorder) InsertSublocalityComponents(request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertSublocalityComponents", reflect.TypeOf((*MockService)(nil).InsertSublocalityComponents), request)
}

// UpdateRestaurantComponents mocks base method.
func (m *MockService) UpdateRestaurantComponents(restaurantId string, request *types.UpdateRestaurantComponentsRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRestaurantComponents", restaurantId, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRestaurantComponents indicates an expected call of UpdateRestaurantComponents.
func (mr *MockServiceMockRecorder) UpdateRestaurantComponents(restaurantId, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRestaurantComponents", reflect.TypeOf((*MockService)(nil).UpdateRestaurantComponents), restaurantId, request)
}

// UpdateSublocalityComponents mocks base method.
func (m *MockService) UpdateSublocalityComponents(sublocalityId string, request *types.UpdateSublocalityComponentsRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSublocalityComponents", sublocalityId, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSublocalityComponents indicates an expected call of UpdateSublocalityComponents.
func (mr *MockServiceMockRecorder) UpdateSublocalityComponents(sublocalityId, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSublocalityComponents", reflect.TypeOf((*MockService)(nil).UpdateSublocalityComponents), sublocalityId, request)
}
