// Code generated by MockGen. DO NOT EDIT.
// Source: ./common.go
//
// Generated by this command:
//
//	mockgen -source=./common.go -destination=./common_mock.go -package=utils
//

// Package utils is a generated GoMock package.
package utils

import (
	reflect "reflect"
	time "time"

	constants "github.com/nutanalabs/eta-service/internal/constants"
	gomock "go.uber.org/mock/gomock"
)

// MockCommonUtils is a mock of CommonUtils interface.
type MockCommonUtils struct {
	ctrl     *gomock.Controller
	recorder *MockCommonUtilsMockRecorder
	isgomock struct{}
}

// MockCommonUtilsMockRecorder is the mock recorder for MockCommonUtils.
type MockCommonUtilsMockRecorder struct {
	mock *MockCommonUtils
}

// NewMockCommonUtils creates a new mock instance.
func NewMockCommonUtils(ctrl *gomock.Controller) *MockCommonUtils {
	mock := &MockCommonUtils{ctrl: ctrl}
	mock.recorder = &MockCommonUtilsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommonUtils) EXPECT() *MockCommonUtilsMockRecorder {
	return m.recorder
}

// GetDayFromTime mocks base method.
func (m *MockCommonUtils) GetDayFromTime(t time.Time) constants.Day {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDayFromTime", t)
	ret0, _ := ret[0].(constants.Day)
	return ret0
}

// GetDayFromTime indicates an expected call of GetDayFromTime.
func (mr *MockCommonUtilsMockRecorder) GetDayFromTime(t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDayFromTime", reflect.TypeOf((*MockCommonUtils)(nil).GetDayFromTime), t)
}

// GetHaversineDistance mocks base method.
func (m *MockCommonUtils) GetHaversineDistance(lat1, lng1, lat2, lng2 float64) float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHaversineDistance", lat1, lng1, lat2, lng2)
	ret0, _ := ret[0].(float64)
	return ret0
}

// GetHaversineDistance indicates an expected call of GetHaversineDistance.
func (mr *MockCommonUtilsMockRecorder) GetHaversineDistance(lat1, lng1, lat2, lng2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHaversineDistance", reflect.TypeOf((*MockCommonUtils)(nil).GetHaversineDistance), lat1, lng1, lat2, lng2)
}

// GetMealTypeFromTime mocks base method.
func (m *MockCommonUtils) GetMealTypeFromTime(t time.Time) constants.MealType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMealTypeFromTime", t)
	ret0, _ := ret[0].(constants.MealType)
	return ret0
}

// GetMealTypeFromTime indicates an expected call of GetMealTypeFromTime.
func (mr *MockCommonUtilsMockRecorder) GetMealTypeFromTime(t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMealTypeFromTime", reflect.TypeOf((*MockCommonUtils)(nil).GetMealTypeFromTime), t)
}

// ToJSON mocks base method.
func (m *MockCommonUtils) ToJSON(data any) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToJSON", data)
	ret0, _ := ret[0].(string)
	return ret0
}

// ToJSON indicates an expected call of ToJSON.
func (mr *MockCommonUtilsMockRecorder) ToJSON(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToJSON", reflect.TypeOf((*MockCommonUtils)(nil).ToJSON), data)
}
