// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/nutanalabs/eta-service/internal/config"
	"github.com/nutanalabs/eta-service/internal/dataclients"
	"github.com/nutanalabs/eta-service/internal/dataclients/mongo"
	"github.com/nutanalabs/eta-service/internal/eta-service"
	"github.com/nutanalabs/eta-service/internal/eta-service/repository"
	"github.com/nutanalabs/eta-service/internal/eta-service/service"
	"github.com/nutanalabs/eta-service/internal/server"
)

// Injectors from di.go:

func InitDependencies() (ServerDependencies, error) {
	configConfig := config.GetConfig()
	serverServer := server.NewServer(configConfig)
	repositoryRepository := repository.NewRepository()
	serviceService := service.NewService(repositoryRepository)
	handler := etaservice.NewHandler(serviceService)
	handlers := server.Handlers{
		ETAHandler: handler,
	}
	client := mongo.NewMongoClient(configConfig)
	dataClients := dataclients.NewDataClients(configConfig, client)
	serverDependencies := ServerDependencies{
		config:      configConfig,
		server:      serverServer,
		handlers:    handlers,
		dataclients: dataClients,
	}
	return serverDependencies, nil
}

// di.go:

type ServerDependencies struct {
	config      *config.Config
	server      *server.Server
	handlers    server.Handlers
	dataclients dataclients.DataClients
}
