// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/nutanalabs/eta-service/internal/config"
	"github.com/nutanalabs/eta-service/internal/dataclients"
	"github.com/nutanalabs/eta-service/internal/dataclients/kafka"
	"github.com/nutanalabs/eta-service/internal/dataclients/mongo"
	"github.com/nutanalabs/eta-service/internal/eta-service"
	"github.com/nutanalabs/eta-service/internal/eta-service/repository"
	"github.com/nutanalabs/eta-service/internal/eta-service/service"
	"github.com/nutanalabs/eta-service/internal/eta-service/validator"
	"github.com/nutanalabs/eta-service/internal/health"
	"github.com/nutanalabs/eta-service/internal/httpclient"
	"github.com/nutanalabs/eta-service/internal/server"
	"github.com/nutanalabs/eta-service/internal/serviceclients/routing-engine"
	"github.com/nutanalabs/eta-service/internal/utils/common"
	utils2 "github.com/nutanalabs/eta-service/internal/utils/http"
)

// Injectors from di.go:

func InitDependencies() (ServerDependencies, error) {
	configConfig := config.GetConfig()
	serverServer := server.NewServer(configConfig)
	client := mongo.NewMongoClient(configConfig)
	mongoRepository := mongo.NewMongoRepository(configConfig, client)
	repositoryRepository := repository.NewRepository(mongoRepository)
	commonUtils := utils.NewCommonUtils()
	httpclientClient := httpclient.NewHTTPClient(configConfig)
	routingEngineClient := routingengine.NewRoutingEngineClient(configConfig, httpclientClient)
	serviceService := service.NewService(repositoryRepository, commonUtils, routingEngineClient, configConfig)
	httpUtils := utils2.NewHttpUtils()
	validatorValidator := validator.NewValidator(configConfig)
	handler := etaservice.NewHandler(serviceService, httpUtils, validatorValidator)
	producerClient, err := kafka.NewKafkaProducerClient(configConfig)
	if err != nil {
		return ServerDependencies{}, err
	}
	dataClients := dataclients.NewDataClients(configConfig, client, producerClient)
	healthHandler := health.NewHandler(dataClients)
	handlers := server.Handlers{
		ETAHandler:    handler,
		HealthHandler: healthHandler,
	}
	serverDependencies := ServerDependencies{
		config:      configConfig,
		server:      serverServer,
		handlers:    handlers,
		dataclients: dataClients,
	}
	return serverDependencies, nil
}

// di.go:

type ServerDependencies struct {
	config      *config.Config
	server      *server.Server
	handlers    server.Handlers
	dataclients dataclients.DataClients
}
