// Code generated by MockGen. DO NOT EDIT.
// Source: ./client.go
//
// Generated by this command:
//
//	mockgen -source=./client.go -destination=./client_mock.go -package=routingengine
//

// Package routingengine is a generated GoMock package.
package routingengine

import (
	reflect "reflect"

	constants "github.com/nutanalabs/eta-service/internal/constants"
	gomock "go.uber.org/mock/gomock"
)

// MockRoutingEngineClient is a mock of RoutingEngineClient interface.
type MockRoutingEngineClient struct {
	ctrl     *gomock.Controller
	recorder *MockRoutingEngineClientMockRecorder
	isgomock struct{}
}

// MockRoutingEngineClientMockRecorder is the mock recorder for MockRoutingEngineClient.
type MockRoutingEngineClientMockRecorder struct {
	mock *MockRoutingEngineClient
}

// NewMockRoutingEngineClient creates a new mock instance.
func NewMockRoutingEngineClient(ctrl *gomock.Controller) *MockRoutingEngineClient {
	mock := &MockRoutingEngineClient{ctrl: ctrl}
	mock.recorder = &MockRoutingEngineClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoutingEngineClient) EXPECT() *MockRoutingEngineClientMockRecorder {
	return m.recorder
}

// GetDistanceMatrix mocks base method.
func (m *MockRoutingEngineClient) GetDistanceMatrix(request *DistanceMatrixRequest) (*DistanceMatrixResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDistanceMatrix", request)
	ret0, _ := ret[0].(*DistanceMatrixResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDistanceMatrix indicates an expected call of GetDistanceMatrix.
func (mr *MockRoutingEngineClientMockRecorder) GetDistanceMatrix(request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDistanceMatrix", reflect.TypeOf((*MockRoutingEngineClient)(nil).GetDistanceMatrix), request)
}

// GetDistanceMatrixWithQoS mocks base method.
func (m *MockRoutingEngineClient) GetDistanceMatrixWithQoS(request *DistanceMatrixRequest, qos constants.QosLevel) (*DistanceMatrixResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDistanceMatrixWithQoS", request, qos)
	ret0, _ := ret[0].(*DistanceMatrixResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDistanceMatrixWithQoS indicates an expected call of GetDistanceMatrixWithQoS.
func (mr *MockRoutingEngineClientMockRecorder) GetDistanceMatrixWithQoS(request, qos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDistanceMatrixWithQoS", reflect.TypeOf((*MockRoutingEngineClient)(nil).GetDistanceMatrixWithQoS), request, qos)
}
