// Code generated by MockGen. DO NOT EDIT.
// Source: ./repository.go
//
// Generated by this command:
//
//	mockgen -source=./repository.go -destination=./repository_mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	reflect "reflect"

	constants "github.com/nutanalabs/eta-service/internal/constants"
	types "github.com/nutanalabs/eta-service/internal/types"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// FetchRestaurantComponents mocks base method.
func (m *MockRepository) FetchRestaurantComponents(restaurantId string, day constants.Day, mealType constants.MealType) (*types.RestaurantComponents, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchRestaurantComponents", restaurantId, day, mealType)
	ret0, _ := ret[0].(*types.RestaurantComponents)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchRestaurantComponents indicates an expected call of FetchRestaurantComponents.
func (mr *MockRepositoryMockRecorder) FetchRestaurantComponents(restaurantId, day, mealType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchRestaurantComponents", reflect.TypeOf((*MockRepository)(nil).FetchRestaurantComponents), restaurantId, day, mealType)
}

// FetchRestaurantComponentsByIDs mocks base method.
func (m *MockRepository) FetchRestaurantComponentsByIDs(restaurantsId []string, cityID, zoneID string, day constants.Day, mealType constants.MealType, batchSize int) ([]types.RestaurantComponents, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchRestaurantComponentsByIDs", restaurantsId, cityID, zoneID, day, mealType, batchSize)
	ret0, _ := ret[0].([]types.RestaurantComponents)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchRestaurantComponentsByIDs indicates an expected call of FetchRestaurantComponentsByIDs.
func (mr *MockRepositoryMockRecorder) FetchRestaurantComponentsByIDs(restaurantsId, cityID, zoneID, day, mealType, batchSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchRestaurantComponentsByIDs", reflect.TypeOf((*MockRepository)(nil).FetchRestaurantComponentsByIDs), restaurantsId, cityID, zoneID, day, mealType, batchSize)
}

// FetchSublocalityComponents mocks base method.
func (m *MockRepository) FetchSublocalityComponents(sublocalityId string, day constants.Day, mealType constants.MealType) (*types.SublocalityComponents, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchSublocalityComponents", sublocalityId, day, mealType)
	ret0, _ := ret[0].(*types.SublocalityComponents)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchSublocalityComponents indicates an expected call of FetchSublocalityComponents.
func (mr *MockRepositoryMockRecorder) FetchSublocalityComponents(sublocalityId, day, mealType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchSublocalityComponents", reflect.TypeOf((*MockRepository)(nil).FetchSublocalityComponents), sublocalityId, day, mealType)
}

// FetchSublocalityComponentsByIDs mocks base method.
func (m *MockRepository) FetchSublocalityComponentsByIDs(sublocalitiesId []string, cityID, zoneID string, day constants.Day, mealType constants.MealType, batchSize int) ([]types.SublocalityComponents, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchSublocalityComponentsByIDs", sublocalitiesId, cityID, zoneID, day, mealType, batchSize)
	ret0, _ := ret[0].([]types.SublocalityComponents)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchSublocalityComponentsByIDs indicates an expected call of FetchSublocalityComponentsByIDs.
func (mr *MockRepositoryMockRecorder) FetchSublocalityComponentsByIDs(sublocalitiesId, cityID, zoneID, day, mealType, batchSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchSublocalityComponentsByIDs", reflect.TypeOf((*MockRepository)(nil).FetchSublocalityComponentsByIDs), sublocalitiesId, cityID, zoneID, day, mealType, batchSize)
}

// InsertRestaurantComponents mocks base method.
func (m *MockRepository) InsertRestaurantComponents(request *types.InsertRestaurantComponentsRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertRestaurantComponents", request)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertRestaurantComponents indicates an expected call of InsertRestaurantComponents.
func (mr *MockRepositoryMockRecorder) InsertRestaurantComponents(request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertRestaurantComponents", reflect.TypeOf((*MockRepository)(nil).InsertRestaurantComponents), request)
}

// InsertSublocalityComponents mocks base method.
func (m *MockRepository) InsertSublocalityComponents(request *types.InsertSublocalityComponentsRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertSublocalityComponents", request)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertSublocalityComponents indicates an expected call of InsertSublocalityComponents.
func (mr *MockRepositoryMockRecorder) InsertSublocalityComponents(request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertSublocalityComponents", reflect.TypeOf((*MockRepository)(nil).InsertSublocalityComponents), request)
}

// PublishFetchEtaEvent mocks base method.
func (m *MockRepository) PublishFetchEtaEvent(eventType constants.EventType, request *types.FetchEtaRequest, response []types.FetchEtaResponse, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PublishFetchEtaEvent", eventType, request, response, err)
}

// PublishFetchEtaEvent indicates an expected call of PublishFetchEtaEvent.
func (mr *MockRepositoryMockRecorder) PublishFetchEtaEvent(eventType, request, response, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishFetchEtaEvent", reflect.TypeOf((*MockRepository)(nil).PublishFetchEtaEvent), eventType, request, response, err)
}

// RestaurantDayOverlapExists mocks base method.
func (m *MockRepository) RestaurantDayOverlapExists(restaurantId string, days []constants.Day) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestaurantDayOverlapExists", restaurantId, days)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RestaurantDayOverlapExists indicates an expected call of RestaurantDayOverlapExists.
func (mr *MockRepositoryMockRecorder) RestaurantDayOverlapExists(restaurantId, days any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestaurantDayOverlapExists", reflect.TypeOf((*MockRepository)(nil).RestaurantDayOverlapExists), restaurantId, days)
}

// SublocalityDayOverlapExists mocks base method.
func (m *MockRepository) SublocalityDayOverlapExists(sublocalityId string, days []constants.Day) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SublocalityDayOverlapExists", sublocalityId, days)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SublocalityDayOverlapExists indicates an expected call of SublocalityDayOverlapExists.
func (mr *MockRepositoryMockRecorder) SublocalityDayOverlapExists(sublocalityId, days any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SublocalityDayOverlapExists", reflect.TypeOf((*MockRepository)(nil).SublocalityDayOverlapExists), sublocalityId, days)
}

// UpdateRestaurantComponents mocks base method.
func (m *MockRepository) UpdateRestaurantComponents(restaurantId string, request *types.UpdateRestaurantComponentsRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRestaurantComponents", restaurantId, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRestaurantComponents indicates an expected call of UpdateRestaurantComponents.
func (mr *MockRepositoryMockRecorder) UpdateRestaurantComponents(restaurantId, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRestaurantComponents", reflect.TypeOf((*MockRepository)(nil).UpdateRestaurantComponents), restaurantId, request)
}

// UpdateSublocalityComponents mocks base method.
func (m *MockRepository) UpdateSublocalityComponents(sublocalityId string, request *types.UpdateSublocalityComponentsRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSublocalityComponents", sublocalityId, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSublocalityComponents indicates an expected call of UpdateSublocalityComponents.
func (mr *MockRepositoryMockRecorder) UpdateSublocalityComponents(sublocalityId, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSublocalityComponents", reflect.TypeOf((*MockRepository)(nil).UpdateSublocalityComponents), sublocalityId, request)
}
