package constants

const (
	VEHICLE_TWO_WHEELER = "TWO_WHEELER"
)

const (
	ROUTING_PREFERENCE_TRAFFIC_AWARE         = "TRAFFIC_AWARE"
	ROUTING_PREFERENCE_TRAFFIC_AWARE_OPTIMAL = "TRAFFIC_AWARE_OPTIMAL"
	ROUTING_PREFERENCE_TRAFFIC_UNAWARE       = "TRAFFIC_UNAWARE"
)